services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app
    depends_on:
      - mysql
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app
  mysql:
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-test_db}'
      MYSQL_USER: '${DB_USERNAME:-test_db}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./:/app/lib/mysql

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  artisan:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    entrypoint: ["php", "/app/artisan"]

  pint:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    entrypoint: ["php", "/app/vendor/bin/pint"]
